### ISSUE TITLE
bug: store response is empty when requests contains invalid cursor

### ISSUE THREAD

**Issue by fbarbu15** [waku-org/nwaku#2117]
### Problem
When passing an invalid cursor to the store query, nwaku sends an empty response back.

Expected: an error in the store response to point towards the invalid cursor issue.

### To reproduce
If you can reproduce the behavior, steps to reproduce:
1. Start nwaku with store protocol
2. Send a query request with a wrong cursor (ex: wrong digest)
3. Get an empty response with no messages

### Expected behavior
INVALID_CURSOR error

### Screenshots/logs
```
waku:store Querying history with the following options {
  cursor: {
    digest: Uint8Array(0) [],
    pubsubTopic: '/waku/2/default-waku/proto',
    senderTime: 1696833269430000000n,
    receiverTime: 1696833269430000000n
  }
} +0ms
  waku:store Querying store peer for (/waku/2/default-waku/proto) [ '/test/1/waku-store/utf8' ] +1ms
  libp2p:upgrader outbound: starting new stream on [ '/vac/waku/store/2.0.0-beta4' ] +51ms
  libp2p:mplex new initiator stream 6 +2ms
  libp2p:upgrader No abort signal was passed while trying to negotiate protocols [ '/vac/waku/store/2.0.0-beta4' ] falling back to default timeout +0ms
  libp2p:upgrader:error Error: stream ended before 1 bytes became available
  libp2p:upgrader:error     at file:///home/fbarbu15/WORK_DIR/js-waku/node_modules/it-reader/src/index.ts:70:9
  libp2p:upgrader:error     at processTicksAndRejections (node:internal/process/task_queues:95:5)
  libp2p:upgrader:error     at async file:///home/fbarbu15/WORK_DIR/js-waku/node_modules/it-length-prefixed/src/decode.ts:118:24
  libp2p:upgrader:error     at async file:///home/fbarbu15/WORK_DIR/js-waku/node_modules/it-first/src/index.ts:14:24
  libp2p:upgrader:error     at async read (file:///home/fbarbu15/WORK_DIR/js-waku/node_modules/@libp2p/multistream-select/src/multistream.ts:77:15)
  libp2p:upgrader:error     at async Module.readString (file:///home/fbarbu15/WORK_DIR/js-waku/node_modules/@libp2p/multistream-select/src/multistream.ts:96:15)
  libp2p:upgrader:error     at async Module.handle (file:///home/fbarbu15/WORK_DIR/js-waku/node_modules/@libp2p/multistream-select/src/handle.ts:65:22)
  libp2p:upgrader:error     at async file:///home/fbarbu15/WORK_DIR/js-waku/node_modules/libp2p/src/upgrader.ts:390:44 +0ms
  libp2p:mplex receiver stream with id 1 and protocol undefined ended +14ms
  libp2p:mplex initiator stream with id 5 and protocol /vac/waku/store/2.0.0-beta4 ended +2ms
  waku:store Stopping pagination due to store `response` field missing +16ms
```
nwaku version/commit hash
v0.20.0

**Comment by alrevuelta** [comment]
Can we reproduce this also with curl and the rest/rpc api?

**Comment by fbarbu15** [comment]
Was able to reproduce with curl as well (notice that the digest is an empty list), thanks for the help:

```
curl http://localhost:8575/ -d '{"jsonrpc": "2.0","id": "id","method": "get_waku_v2_store_v1_messages","params": ["/waku/2/dev-waku/proto", [{"contentTopic": "ethcc-topic"}], null, null, {"pageSize": 10, "cursor": {"digest": {"data": []}, "pubsubTopic": "/waku/2/default-waku/proto", "senderTime": 1696843954429000000, "receiverTime": 1696843954429000000},"forward": false}]}' --header "Content-Type: application/json"

{"jsonrpc":"2.0","id":"id","result":{"messages":[],"pagingOptions":null}
```

**Comment by Ivansete-status** [comment]
Thanks for submitting that with so great detail @fbarbu15 !
The issue happens because we are using a fixed array length inside the `nwaku` code:
https://github.com/waku-org/nwaku/blob/6da1aeec5370bb1c116509e770178cca2662b69c/waku/waku_store/common.nim#L28

With that, even if you send empty data within the cursor, it gets automatically filled with zeros, as can be seen in the next (I added a local temporary debug log line to see that :)
```
some((pubsubTopic: \"/waku/2/default-waku/proto\", senderTime: 1696843954429000000, receiverTime: 1696843954429000000, digest: (data: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])))
```

I can enhance the response for that particular case.
However, if you needed to detect the following:
```
curl http://localhost:8546/ -d '{"jsonrpc": "2.0","id": "id","method": "get_waku_v2_store_v1_messages","params": ["/waku/2/dev-waku/proto", [{"contentTopic": "ethcc-topic"}], null, null, {"pageSize": 10, "cursor": {"digest": {"data": [12]}, "pubsubTopic": "/waku/2/default-waku/proto", "senderTime": 1696843954429000000, "receiverTime": 1696843954429000000},"forward": false}]}' --header "Content-Type: application/json"
```

That would require a bigger change in the store protocol implementation.

@fbarbu15 - Would that suffice or would you need a wider validation?

**Comment by fbarbu15** [comment]
I think having empty digest is more likely and having nwaku behave like go-waku in this scenario and return INVALID_CURSOR would be enough.
Thanks
