### ISSUE TITLE
Prepare release 0.24.0

### ISSUE THREAD

**Issue by SionoiS** [waku-org/nwaku#2343]
### Items to complete
- [ ] create release branch
- [ ] assign release candidate tag
- [ ] validate release candidate
- [ ] generate and edit releases notes
- [ ] open PR and merge release notes to master
- [ ] cherry-pick release notes to the release branch
- [ ] assign release tag to the cherry-picked release notes commit
- [ ] create GitHub release
- [ ] deploy the release to DockerHub
- [ ] deploy release to `wakuv2.prod` fleet
- [ ] announce the release

**Comment by SionoiS** [comment]
It seams like we are having some problems.
```
1) Waku Filter V2 (Named sharding): Multiple PubsubTopics
2024-01-10T16:03:41.7398469Z        "before each" hook for "Subscribe and receive messages on custom pubsubtopic":
2024-01-10T16:03:41.7399850Z      TypeError: Cannot read properties of undefined (reading 'id')
2024-01-10T16:03:41.7401422Z       at Filter.createSubscription (file:///home/runner/work/nwaku/nwaku/packages/core/src/lib/filter/index.ts:313:52)
2024-01-10T16:03:41.7402931Z       at processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-01-10T16:03:41.7404602Z       at async Context.<anonymous> (file:///home/runner/work/nwaku/nwaku/packages/tests/tests/filter/multiple_pubsub.node.spec.ts:289:24)
2024-01-10T16:03:41.7405849Z 
2024-01-10T16:03:41.7406180Z   2) Waku Store (named sharding), custom pubsub topic
2024-01-10T16:03:41.7406915Z        Generator, custom pubsub topic:
2024-01-10T16:03:41.7407328Z 
2024-01-10T16:03:41.7407983Z       AssertionError: expected +0 to equal 20
2024-01-10T16:03:41.7408684Z       + expected - actual
2024-01-10T16:03:41.7408995Z 
2024-01-10T16:03:41.7409170Z       -0
2024-01-10T16:03:41.7409501Z       +20
2024-01-10T16:03:41.7409834Z       
2024-01-10T16:03:41.7410981Z       at Context.<anonymous> (file:///home/runner/work/nwaku/nwaku/packages/tests/tests/store/multiple_pubsub.spec.ts:219:34)
2024-01-10T16:03:41.7412569Z       at processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-01-10T16:03:41.7413238Z 
2024-01-10T16:03:41.7413563Z   3) Waku Store (named sharding), custom pubsub topic
2024-01-10T16:03:41.7414521Z        Generator, 2 different pubsubtopics:
2024-01-10T16:03:41.7414967Z 
2024-01-10T16:03:41.7415235Z       AssertionError: expected +0 to equal 10
2024-01-10T16:03:41.7415903Z       + expected - actual
2024-01-10T16:03:41.7416211Z 
2024-01-10T16:03:41.7416375Z       -0
2024-01-10T16:03:41.7416708Z       +10
2024-01-10T16:03:41.7417040Z       
2024-01-10T16:03:41.7418182Z       at Context.<anonymous> (file:///home/runner/work/nwaku/nwaku/packages/tests/tests/store/multiple_pubsub.spec.ts:235:40)
2024-01-10T16:03:41.7419738Z       at processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-01-10T16:03:41.7420402Z 
2024-01-10T16:03:41.7420724Z   4) Waku Store (named sharding), custom pubsub topic
2024-01-10T16:03:41.7421607Z        Generator, 2 nwaku nodes each with different pubsubtopics:
2024-01-10T16:03:41.7422492Z      Error: stream ended before 1 bytes became available
2024-01-10T16:03:41.7423990Z       at file:///home/runner/work/nwaku/nwaku/node_modules/it-reader/src/index.ts:70:9
2024-01-10T16:03:41.7425261Z       at processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-01-10T16:03:41.7427159Z       at async abortable (file:///home/runner/work/nwaku/nwaku/node_modules/abortable-iterator/src/index.ts:90:18)
2024-01-10T16:03:41.7428994Z       at async file:///home/runner/work/nwaku/nwaku/node_modules/it-length-prefixed/src/decode.ts:118:24
2024-01-10T16:03:41.7430590Z       at async file:///home/runner/work/nwaku/nwaku/node_modules/it-first/src/index.ts:14:24
2024-01-10T16:03:41.7432654Z       at async read (file:///home/runner/work/nwaku/nwaku/node_modules/@libp2p/multistream-select/src/multistream.ts:77:15)
2024-01-10T16:03:41.7436766Z       at async Module.readString (file:///home/runner/work/nwaku/nwaku/node_modules/@libp2p/multistream-select/src/multistream.ts:96:15)
2024-01-10T16:03:41.7438409Z       at async Module.select (file:///home/runner/work/nwaku/nwaku/node_modules/@libp2p/multistream-select/src/select.ts:76:18)
2024-01-10T16:03:41.7439606Z       at async ConnectionImpl.newStream [as _newStream] (file:///home/runner/work/nwaku/nwaku/node_modules/libp2p/src/upgrader.ts:453:40)
2024-01-10T16:03:41.7440786Z       at async ConnectionImpl.newStream (file:///home/runner/work/nwaku/nwaku/node_modules/libp2p/src/connection/index.ts:134:20)
```

Do we need to change the js-waku tests?

**Comment by SionoiS** [comment]
done
